# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  softplanapi1:
    image: softplanapi1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080